=== DockerFile

.构建
[source,bash]
----
docker build -d 新镜像名字:TAG .
----

.CentOS7JDK11脚本
[source,bash]
----
FROM centos:centos7
MAINTAINER ylighgh<yssuvu@gmail.com>

ENV MYPATH /usr/local
WORKDIR $MYPATH

RUN yum -y update
RUN yum -y install vim
RUN yum -y install net-tools
RUN mkdir /usr/local/java
ADD jdk-11.0.15.1_linux-x64_bin.tar.gz /usr/local/java
ENV JAVA_HOME /usr/local/java/jdk-11.0.15.1
ENV CLASSPATH $JAVA_HOME/lib/tools.jar:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib
ENV PATH $JAVA_HOME/bin:$PATH


CMD echo $MYPATH
CMD echo "sucess------ok"
CMD /bin/bash
----